### ISSUE TITLE
App on mobile

### ISSUE THREAD

**Issue by codewithbisal** [ashutosh1919/masterPortfolio#316] opened 2023-08-31 06:58 UTC
I cant access menu and proper alignment when i open website on mobile

**Comment by dhruvkrishnavaid** [comment] 2023-09-03 02:50
Can't reproduce. Attach screenshots.

**Comment by ashutosh1919** [comment] 2023-10-04 00:25
Closing due to nonsignificant information. @codewithbisal please reopen with details of the errors

**Closed by ashutosh1919** 2023-10-04 00:25 UTC
