### ISSUE TITLE
There is a horizontal scroll in "open-source" page in mobile view. Its due to the PullRequest and IssueRequest pie chart CSS. Fix it!

### ISSUE THREAD

**Issue by vanoop729** [ashutosh1919/masterPortfolio#124] opened 2021-06-24 13:01 UTC
Look into the CSS part of IssueRequest and PullRequest

**Comment by vanoop729** [comment] 2021-06-24 13:03
Can I open a Pull Request for the same, @ashutosh1919 ?

**Comment by ashutosh1919** [comment] 2021-06-24 13:03
@vanoop729 , If you want to contribute, Please feel free to raise PR

**Comment by vanoop729** [comment] 2021-06-24 13:03
Will do!

**Comment by vanoop729** [comment] 2021-07-29 17:20
This is how I customized it: [https://anoopv.me/](https://anoopv.me/)

**Comment by saiteja13427** [comment] 2022-06-12 18:06
Reviewed and merged the respective PR!

Thanks, @vanoop729 

The issue is now solved.

Thus closing this issue!

**Closed by saiteja13427** 2022-06-12 18:06 UTC
