### ISSUE TITLE
Unable to fetch data from GitHub

### ISSUE THREAD

**Issue by SmritiAgrawal04** [ashutosh1919/masterPortfolio#24] opened 2020-07-23 04:59 UTC
I've followed all the steps in order to fetch the data from github- 
1) Installed node.js  and npm.
2) Ran npm install after cloning the repo.
3) Issued a Personal Access Token with all the access to it.
4) Replaced the PAT and Github username in git_data_fetcher.js and ran the command- node git_data_fetcher.js.

But still it isn't fetching any of my repositories. Although there is no error popping up. Please let me know the solution to resolve the issue asap. Thanks.

**Comment by ashutosh1919** [comment] 2020-07-23 06:28
Closing this one as duplicate of #21 . Please share your thoughts on the original issue #21.

**Closed by ashutosh1919** 2020-07-23 06:28 UTC
