### ISSUE TITLE
How do I change the fileName in portfolio.js skills set

### ISSUE THREAD

**Issue by Kapoor-0905** [ashutosh1919/masterPortfolio#273] opened 2023-01-24 05:19 UTC

**Comment by ashutosh1919** [comment] 2023-01-24 16:53
@Kapoor-0905 You need to create separate React component as other components are already created. Please look at the code. 

Closing this as of now. Feel free to reopen this if you think the problem is not resolved.

**Closed by ashutosh1919** 2023-01-24 16:53 UTC
